spring.application.name=telemetry-service

mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=telemetry-service
mqtt.topic=smartroom/telemetry/#
mqtt.qos=1

logging.level.org.springframework.integration.mqtt=DEBUG
logging.level.com.smartroom.telemetry_service=DEBUG
